//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> SexoID { get; set; }
        public decimal Peso { get; set; }
        public decimal Estatura { get; set; }
        public decimal BMI { get; set; }
        public decimal BMR { get; set; }
        public Nullable<int> NivelActividad { get; set; }
    
        public virtual NIVEL_ACTIVIDAD NIVEL_ACTIVIDAD { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
